version: '3.8'
services:

  redis:
    image: redis:latest
    container_name: redis_cache_ticket
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_cache_ticket:/data

volumes:
  redis_cache_ticket:
